# Generated by Django 4.0.2 on 2022-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path_users', models.CharField(blank=True, db_column='Photo_Path_Users', max_length=255, null=True)),
            ],
            options={
                'db_table': 'User_Media_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkMediaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path_work', models.CharField(blank=True, db_column='Photo_Path_Work', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Work_Media_List',
                'managed': False,
            },
        ),
    ]
