# Generated by Django 3.2.12 on 2022-04-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_media_list',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='work_media_list',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='user_media_list',
            table='User_Media_List',
        ),
        migrations.AlterModelTable(
            name='work_media_list',
            table='Work_Media_List',
        ),
    ]
