# Generated by Django 4.0.4 on 2022-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_libraryuserprofile_delete_libraryuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id_users",
                    models.CharField(
                        db_column="ID_Users",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(db_column="Password_Hash", max_length=32),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
                (
                    "first_name",
                    models.CharField(db_column="First_Name", max_length=100),
                ),
                ("date_birth", models.DateField(db_column="Date_Birth")),
                (
                    "fees",
                    models.DecimalField(
                        db_column="Fees", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "email",
                    models.CharField(db_column="Email", max_length=320, unique=True),
                ),
                (
                    "addresse_postale",
                    models.CharField(db_column="Addresse_Postale", max_length=6),
                ),
                (
                    "expiration_subscription",
                    models.DateField(db_column="Expiration_Subscription"),
                ),
                (
                    "permissions",
                    models.CharField(db_column="Permissions", max_length=2),
                ),
                (
                    "related_library_id",
                    models.CharField(
                        blank=True,
                        db_column="Related_Library_ID",
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "User_List",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="LibraryUserProfile",
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="librariesdata",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="loanedworks",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="worklist",
            options={"managed": True},
        ),
    ]
