# Generated by Django 3.2.12 on 2022-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220425_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path_users', models.CharField(blank=True, db_column='Photo_Path_Users', max_length=255, null=True)),
            ],
            options={
                'db_table': 'User_Media_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkMediaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path_work', models.CharField(blank=True, db_column='Photo_Path_Work', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Work_Media_List',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='work_media_list',
            name='id_works',
        ),
        migrations.DeleteModel(
            name='User_Media_List',
        ),
        migrations.DeleteModel(
            name='Work_Media_List',
        ),
    ]
